### ISSUE TITLE
Duplicate reconciliation when object is updated or added

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/astro#72]
I've noticed this behavior for a while and finally started looking into it but can't figure out why it's happening. The below logs are generated when updating the `kstats-2` deployment in the `kstats` namespace. It runs [this UpdateFunc code](https://github.com/FairwindsOps/astro/blob/master/pkg/controller/controller.go#L199) twice which also causes the [reconciliation code](https://github.com/FairwindsOps/astro/blob/master/pkg/handler/deployments.go#L45) to run twice. Any ideas on this? I can't seem to find anything in the code that would cause this, but I could be missing something.

```
INFO[0033] deployment/kstats/kstats-2 has been updated. 
INFO[0033] Handler got an OnUpdate event of type deployment 
INFO[0033] Loading rulesets from conf.yml               
INFO[0033] deployment/kstats/kstats-2 has been updated. 
INFO[0033] Annotation astro/admin with value fairwinds does not exist, so monitor 1 does not match 
INFO[0033] Reconcile monitor Deployment Replica Alert - kstats-2 
INFO[0033] Update templated monitor: Deployment Replica Alert - kstats-2 
INFO[0033] Monitor 14633828 needs updating.             
INFO[0033] Handler got an OnUpdate event of type deployment 
INFO[0033] Loading rulesets from conf.yml               
INFO[0033] Annotation astro/admin with value fairwinds does not exist, so monitor 1 does not match 
INFO[0033] Reconcile monitor Deployment Replica Alert - kstats-2 
INFO[0033] Update templated monitor: Deployment Replica Alert - kstats-2 
INFO[0033] Monitor 14633828 needs updating.
```

**Comment by rbren** [comment]
Any more details you can give that would help reproduce? I tried adding a test case that updates a deployment, but I don't see a duplicate `deployment/owned-namespace/foo has been updated`

Does it happen on DRY_RUN, or only when running live? My only thought is that a change in DataDog could somehow trigger a second update to the deployment.

**Comment by rbren** [comment]
Also, FYI, the test case: https://github.com/FairwindsOps/astro/blob/rb/debug/pkg/controller/controller_test.go#L66

It doesn't actually test anything, but it triggers the logs at least.

Also, TIL - if you quickly create and delete a deployment, the Informer's handlers won't get triggered at all! Hence the time.Sleeps in the test.

**Comment by lucasreed** [comment]
Looks like the `metadata.resourceVersion` of my test object iterates two times on a single `kubectl edit` so it may be expected behavior and we need to account for it in the app itself. My concern is that these changes will cause a larger-than-necessary amount of API calls to the datadog api (even if they are just GETs).

For reference I'm running a [kind cluster](https://github.com/kubernetes-sigs/kind) for my testing and the behavior appears in both dry and live modes of astro.

**Comment by lucasreed** [comment]
In writing the changes for #74 I concluded that the kubernetes API is in fact NOT updating the revision twice that I can find, unless it's specific to changing the annotations. If I update a label on the deployment spec, it only seems to run once.

**Comment by lucasreed** [comment]
With further testing, it appears that changing annotations specifically is what causes the revision number to go up two times. If I update a label on a monitored deployment, the OnUpdate() function only appears to run once.

**Comment by lucasreed** [comment]
Reopened because that PR didn't really fix the underlying issue. There may not BE an issue, but I'd like to get to the bottom of why annotation changes seem to trigger two updates of the `resourceVersion`. Could be a kube thing or it could be something in our `OnUpdate()` call that does it. Either way I'd like to poke around some more even though most of the issues are mitigated at this point.

**Comment by lucasreed** [comment]
I think this is mostly accounted for at this point and the API calls out to datadog have been lowered with #74
