### ISSUE TITLE
Static global monitors in config file

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/astro#78]
This is something @mjhuber and I were chatting about recently. Right now in the example config we have things like master node High System Load Average listed as namespaced monitors which really doesn't make sense to me.

I was thinking having a new config section for static monitors that don't rely on kube state would make sense here. This would allow all monitoring for a given cluster to be fully defined and owned by astro without the weird namespaced workaround we currently have.

Interested in opinions on this.

**Comment by mjhuber** [comment]
i like this idea and would make it much easier to monitor things that aren't coupled to a kubernetes object

**Comment by lucasreed** [comment]
Added in #113
